/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicTemplatesRouteImport } from './routes/api/public/templates'
import { Route as ApiPublicTransformRouteImport } from './routes/api/public/transform'
import { Route as ApiPublicUsageRouteImport } from './routes/api/public/usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTemplatesRoute = ApiPublicTemplatesRouteImport.update({
  id: '/api/public/templates',
  path: '/api/public/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTransformRoute = ApiPublicTransformRouteImport.update({
  id: '/api/public/transform',
  path: '/api/public/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUsageRoute = ApiPublicUsageRouteImport.update({
  id: '/api/public/usage',
  path: '/api/public/usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/templates': typeof ApiPublicTemplatesRoute
  '/api/public/transform': typeof ApiPublicTransformRoute
  '/api/public/usage': typeof ApiPublicUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/templates': typeof ApiPublicTemplatesRoute
  '/api/public/transform': typeof ApiPublicTransformRoute
  '/api/public/usage': typeof ApiPublicUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/templates': typeof ApiPublicTemplatesRoute
  '/api/public/transform': typeof ApiPublicTransformRoute
  '/api/public/usage': typeof ApiPublicUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/library'
    | '/api/public/feedback'
    | '/api/public/templates'
    | '/api/public/transform'
    | '/api/public/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/library'
    | '/api/public/feedback'
    | '/api/public/templates'
    | '/api/public/transform'
    | '/api/public/usage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/connect'
    | '/_authenticated/library'
    | '/api/public/feedback'
    | '/api/public/templates'
    | '/api/public/transform'
    | '/api/public/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicTemplatesRoute: typeof ApiPublicTemplatesRoute
  ApiPublicTransformRoute: typeof ApiPublicTransformRoute
  ApiPublicUsageRoute: typeof ApiPublicUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/templates': {
      id: '/api/public/templates'
      path: '/api/public/templates'
      fullPath: '/api/public/templates'
      preLoaderRoute: typeof ApiPublicTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transform': {
      id: '/api/public/transform'
      path: '/api/public/transform'
      fullPath: '/api/public/transform'
      preLoaderRoute: typeof ApiPublicTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/usage': {
      id: '/api/public/usage'
      path: '/api/public/usage'
      fullPath: '/api/public/usage'
      preLoaderRoute: typeof ApiPublicUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicTemplatesRoute: ApiPublicTemplatesRoute,
  ApiPublicTransformRoute: ApiPublicTransformRoute,
  ApiPublicUsageRoute: ApiPublicUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
